---
title: "20221030_Export_Forecast_with_R"
author: "Felipe Tufaile, Vinicius de Camargo, Helena Funari, Rodrigo Zamengo"
date: "`r Sys.Date()`"
output: html_document
---

### R Markdown


```{r configs, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, include = TRUE, message = FALSE)
```

### Including Plots

You can also embed plots, for example:

```{r libraries}

## Set working directory
setwd("~/Insper/Commodity_Export_Forecast")

library(dplyr)
library(tidyverse)
library(ggthemes)
library(fpp3)
library(forecast)
library(gridExtra)
library(ggpubr)
library(tseries)
```
### Defining Functions

```{r functions}

## Creating function for adding time series to ggplots
add_serie <- function(data, xdata, ydata, name, color, text_position, labels) {

  list(geom_line(data=data, aes(x=.data[[xdata]], y=.data[[ydata]], color=name), linetype="solid", alpha=0.8),
       geom_text(data=data, aes(x=.data[[xdata]], y=.data[[ydata]], label=.data[[labels]]),
                 colour = color,
                 size=2.5, 
                 vjust=ifelse(text_position=="Above", -1, 2), hjust=0.5))
}

## Defining custom x-labels for time series plot without lag
time_series_xlabels <- function(){
  scale_x_date(breaks=seq(from=as.Date("1997-01-01"), to=as.Date("2022-01-01"), by = "12 month"), 
               date_label = "%b\n%y", expand=expansion(mult = c(0.02, 0.02)))
}

## Defining custom themes
time_series_theme <- function(){
  theme_hc() +
  theme(plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major.y = element_line(colour = '#E6E7E8'),
        panel.grid.minor.y = element_line(colour = '#E6E7E8'),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.line.y = element_line(colour = '#000000'),
        axis.line.x = element_line(colour = '#000000'),
        axis.text.y = element_text(colour = '#000000', size=8),
        axis.ticks.y = element_line(colour = '#000000'),
        axis.title.y = element_text(colour = '#000000', size=8),
        legend.position = "bottom",
        plot.title = element_text(colour = "#000000", size=14),
        plot.subtitle = element_text(colour = '#585858', size=12),
        text = element_text(colour = '#585858', size=9),
        axis.text = element_text(colour = '#585858', size=8))
  }
```


### Data Loading

```{r loading_dataset}
# Reading export dataset
export <- read_csv("export_database.csv")

# Selecting soy bean production in midwest
midwest_soybean <- export %>% 
  filter(produto == 'COMPLEXO SOJA' & regiao == 'CENTRO-OESTE' & ref_ano >= 2000 & ref_ano <= 2021) %>%
  group_by(ref_date_fmd) %>%
  summarize(vl_mm_ton = sum(massa_exportada_kg)/10^9)

```


### Plotting time-series

```{r plotting_series_01, out.width="100%"}
## Plotting
plot <- ggplot() +
  add_serie(data=midwest_soybean %>% mutate(labels = ""), 
            xdata="ref_date_fmd", 
            ydata="vl_mm_ton", 
            name='Soy Bean Export', 
            color="#009491", 
            text_position="Above", 
            labels="labels") +
  scale_color_manual(name="", breaks=c('Soy Bean Export'), values=c('#009491')) +
  time_series_xlabels() +
  scale_y_continuous(limits=c(0, 10), breaks=seq(0, 10, 1), minor_breaks=seq(0, 10, 0.5)) +
  labs(x = "", 
       y = "Soy Bean Export (MM Ton)",
       title="Soy Bean Export in Midwest of Brazil from Jan-2000 to Dec-2021",
       subtitle="") +
  time_series_theme()

plot
```


### Applying a boxcox transformation on the time-series

```{r boxcox, out.width="100%"}
## Calculating boxcox transformation on vl_mm_ton
boxcox_transform <- BoxCox(midwest_soybean$vl_mm_ton, lambda = "auto")

## Creating a new tibble with the transformed vl_mm_ton value
midwest_soybean_boxcox <- tibble(ref_date_fmd = midwest_soybean$ref_date_fmd,
                                 vl_mm_ton_boxcox = c(boxcox_transform))

## Plotting
plot <- ggplot() +
  add_serie(data=midwest_soybean_boxcox %>% mutate(labels = ""), 
            xdata="ref_date_fmd", 
            ydata="vl_mm_ton_boxcox", 
            name="Soy Bean Export", 
            color="#009491", 
            text_position="Above", 
            labels="labels") +
  scale_color_manual(name="", breaks=c('Soy Bean Export'), values=c('#009491')) +
  time_series_xlabels() +
  scale_y_continuous(limits=c(-3, 3), breaks=seq(-3, 3, 1), minor_breaks=seq(-3, 3, 0.5)) +
  labs(x = "", 
       y = "Soy Bean Export (MM Ton)",
       title=paste('Soy Bean Export in Midwest of Brazil | Boxcox with lambda=', round(attributes(boxcox_transform)$lambda,2)),
       subtitle="") +
  time_series_theme()

plot
```


```{r qqplot, out.width="100%"}
df_hist = rbind(tibble(vl_mm_ton = as.double(midwest_soybean$vl_mm_ton), type = "Original"), 
                tibble(vl_mm_ton = as.double(midwest_soybean_boxcox$vl_mm_ton_boxcox), type = "BoxCox"))
ggplot(df_hist, aes(sample = vl_mm_ton)) +
geom_qq() +
geom_qq_line() +
facet_grid(type ~ ., scales = "free_y") +
ggtitle("QQ plot: Original and transformed data", "BoxCox transform improved normality")

```


### Plotting ACF and PACF plots on the original time-series

```{r creating_time_series, out.width="100%"}
## Building time series object on exporting data
midwest_soybean_tsibble <- midwest_soybean %>%
    select(ref_date_fmd, vl_mm_ton) %>%
    dplyr::mutate(ref_date_fmd = tsibble::yearmonth(ref_date_fmd)) %>%
    tsibble::as_tsibble(index=ref_date_fmd)

## Using the tsibble time series object
print(midwest_soybean_tsibble %>% fabletools::features(.tbl=., .var=vl_mm_ton, features=list(unitroot_kpss, unitroot_ndiffs)))

## Plotting the auto-correlation function and partial auto-correlation function for the export time series with one difference
midwest_soybean_tsibble %>%
  gg_tsdisplay(vl_mm_ton, plot_type='partial')
```

```{r}
tseries::adf.test(midwest_soybean_boxcox$vl_mm_ton_boxcox,
                  alternative = c("stationary", "explosive"), 
                  k = trunc((length(midwest_soybean_boxcox$vl_mm_ton_boxcox)-1)^(1/3)))
```


### Plotting ACF and PACF plots on the time-series difference one time

```{r differencing_time_series, out.width="100%"}
## Using the tsibble time series object
print(midwest_soybean_tsibble %>% fabletools::features(.tbl=., .var=difference(vl_mm_ton), features=list(unitroot_kpss, unitroot_ndiffs)))

## Plotting the auto-correlation function and partial auto-correlation function for the export time series with one difference
midwest_soybean_tsibble %>%
  gg_tsdisplay(difference(vl_mm_ton), plot_type='partial')
```


## Studying seasonality

```{r cartesian_seasonal_chart, out.width="100%"}
## Plotting monthly seasonal chart using library feasts | Cartesian view
midwest_soybean_tsibble %>% 
  feasts::gg_season(y=vl_mm_ton)
```

```{r polar_seasonal_chart, out.width="100%"}
## Plotting monthly seasonal chart using library feasts | Polar view
midwest_soybean_tsibble %>% 
  feasts::gg_season(y=vl_mm_ton, polar=TRUE)
```

```{r time_series_decomposition, out.width="100%"}
## Using STL model from fpp3
dcmp <- midwest_soybean_tsibble %>%
  model(stl = STL(vl_mm_ton))

components(dcmp) %>% autoplot()
```

```{r time_series_boxcox_time_series, out.width="100%"}
## Building time series object on exporting data
midwest_soybean_boxcox_tsibble <- midwest_soybean_boxcox %>%
    select(ref_date_fmd, vl_mm_ton_boxcox) %>%
    dplyr::mutate(ref_date_fmd = tsibble::yearmonth(ref_date_fmd)) %>%
    tsibble::as_tsibble(index=ref_date_fmd)

## Using STL model from fpp3
dcmp_boxcox <- midwest_soybean_boxcox_tsibble %>%
  model(stl = STL(vl_mm_ton_boxcox))

components(dcmp_boxcox) %>% autoplot()
```


```{r comparing_datasets, out.width="100%"}
## Original dataset
plot_original <- midwest_soybean_tsibble %>%
  autoplot(vl_mm_ton) +
  geom_smooth() +
  ggtitle("Original scale")

## Transformed dataset
plot_boxcox <- midwest_soybean_boxcox_tsibble %>%
  autoplot(vl_mm_ton_boxcox) +
  geom_smooth() +
  ggtitle(paste("Box Cox with lambda = ", round(attributes(boxcox_transform)$lambda,2)))

## Comparision
plot <- ggarrange(plot_original, plot_boxcox, ncol=2, nrow=1, widths=c(1,1), common.legend = FALSE)

annotate_figure(plot, top=text_grob("Soy Bean Export in Midwest of Brazil", 
                                    color="#000000", 
                                    size=14, 
                                    x=unit(0.5, "lines"), 
                                    y=unit(0, "lines"), 
                                    just="left", 
                                    hjust=0, 
                                    vjust=0))

```
